SELECT * FROM bike_sales.sales;

-- Changing table name 

rename table sales to bike_parts_sales;

SELECT * FROM bike_parts_sales;

-- Sales Overview:

-- 1) What is the total revenue generated by each warehouse location?

SELECT 
    warehouse, ROUND(SUM(total),2)total_revenue
FROM
    bike_parts_sales
GROUP BY warehouse;

-- 2 What is the total quantity of products sold by each warehouse location?

SELECT 
    warehouse, SUM(quantity) total_qty
FROM
    bike_parts_sales
GROUP BY warehouse;
    
-- 3 How does the total sales (quantity, revenue) compare between retail and wholesale clients?

SELECT 
    client_type, ROUND(SUM(total),2) total_sale, SUM(quantity)total_quantity
FROM
    bike_parts_sales
GROUP BY client_type
ORDER BY total_sale DESC;

-- Product Line Performance:

-- 4 Which product line generates the highest revenue?

SELECT 
    product_line, ROUND(SUM(total), 2) AS total_revenue
FROM
    bike_parts_sales
GROUP BY product_line
ORDER BY total_revenue DESC;

-- 5 What is the average unit price for each product line?

SELECT 
    product_line, ROUND(AVG(unit_price),2) AS avg
FROM
    bike_parts_sales
GROUP BY product_line;

-- 6 How do product sales (quantity and revenue) differ across warehouse locations?  

SELECT 
    warehouse, product_line, ROUND(SUM(total), 2) total_sale
FROM
    bike_parts_sales
GROUP BY warehouse , product_line;

-- Customer Type Insights:

-- 7 What is the distribution of sales between retail and wholesale clients for each product line?

SELECT 
    client_type, product_line, ROUND(SUM(total), 2) AS revenue
FROM
    bike_parts_sales
GROUP BY client_type , product_line
ORDER BY client_type , revenue DESC;

-- Pricing and Revenue:

-- 8 What is the average total price per sale by warehouse location?

SELECT 
    warehouse, ROUND(AVG(total), 2)
FROM
    bike_parts_sales
GROUP BY warehouse;

-- 9 How does the unit price vary across different product lines and warehouse locations? 

SELECT 
     warehouse , product_line, ROUND(SUM(unit_price),2)total
FROM
    bike_parts_sales
GROUP BY warehouse ,product_line;

-- Payment Method Analysis:

-- 10 What are the most common payment methods used by customers, and how do they vary by location ?

SELECT 
    warehouse, payment, COUNT(payment)as cnt
FROM
    bike_parts_sales
GROUP BY payment , warehouse
ORDER BY cnt DESC;

-- 11 What is the average payment fee associated with each payment method?

SELECT 
    payment, ROUND(AVG(payment_fee), 2)total_fee
FROM
    bike_parts_sales
GROUP BY payment;

-- 12 How do payment methods differ between retail and wholesale clients?

SELECT 
    client_type, payment, COUNT(payment)no_of_payment
FROM
    bike_parts_sales
GROUP BY client_type, payment;

-- Fees and Charges:

-- 13 What is the total payment fee collected from each warehouse location?

SELECT 
    warehouse, ROUND(SUM(payment_fee),2) total_fee
FROM
    bike_parts_sales
GROUP BY warehouse;

-- What percentage of total sales is accounted for by payment fees?

      -- PENDING
      
-- Time-Based Trends (if timestamp data exists):      
      
-- 14 Month on montth increase and decrease in sale

SELECT 
   month(date)month_no , ROUND(SUM(total),2)total_sale,
	 ROUND(SUM(total) - LAG(SUM(total)) OVER (ORDER BY month(date)),2) diff
   FROM bike_parts_sales
GROUP BY month_no;

-- 15 What are the peak sales periods (month) for each product line?

SELECT 
    MONTH(date) mth, ROUND(SUM(total), 2) total
FROM
    bike_parts_sales
GROUP BY mth
ORDER BY total DESC;

-- Warehouse-Specific Insights:

-- 16 Which warehouse location generates the most revenue for each product line?

SELECT 
    warehouse, product_line, ROUND(SUM(total), 2) total_sale
FROM
    bike_parts_sales
GROUP BY warehouse , product_line
ORDER BY total_sale DESC, warehouse;

-- 17 Featch all the data where sale is greter than average sale

SELECT 
    *
FROM
    bike_parts_sales
WHERE
    total > (SELECT 
            AVG(total) total
        FROM
            bike_parts_sales) 
            
--                                     END OF PROJECT                                               --

